manifest:
  version: "0.13"
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.4.2
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic
  self:
    path: manifest
