"""Generate the fixed OpenDisplay config container (CRC-16/CCITT-FALSE)."""
from pathlib import Path
import binascii
import struct


def config_bytes():
    # Unknown/custom MCU ID: do not impersonate a supported nRF52 for OTA.
    system = struct.pack("<HBBB15sBB", 0xFFFF, 1, 0, 255, bytes(15), 255, 255)
    manufacturer = bytes(22)
    power = bytearray(30)
    power[0] = 1  # battery; capacity unknown
    power[8:10] = b"\xff\xff"
    power[11] = 4  # primary lithium
    power[20:22] = b"\xff\xff"
    display = bytearray(46)
    display[1] = 1  # e-paper
    struct.pack_into("<HHHHH", display, 2, 19, 104, 212, 23, 48)
    display[15:25] = bytes([3, 4, 2, 1, 30, 1, 0, 0x1b, 0, 255])
    body = bytearray([0, 0, 1])
    for kind, payload in [(1, system), (2, manufacturer), (4, power), (32, display)]:
        body += bytes([0, kind]) + payload
    crc = binascii.crc_hqx(body, 0xFFFF)
    body += struct.pack("<H", crc)
    struct.pack_into("<H", body, 0, len(body))
    return bytes(body)


if __name__ == "__main__":
    data = config_bytes()
    lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 12]) for i in range(0, len(data), 12)]
    text = "/* Generated by scripts/generate_config.py; fixed board configuration. */\n"
    text += "static const uint8_t od_config[] = {\n    " + ",\n    ".join(lines) + "\n};\n"
    (Path(__file__).resolve().parents[1] / "src/config.inc").write_text(text)
